# BuildFox ninja generator

def gen_make(filename = "Makefile"):
	text = r"""# generated by BuildFox
all: configure compile
configure:
	bf
compile:
	ninja
clean:
	ninja -t clean
"""
	with open(filename, "w") as f:
		f.write(text)