# BuildFox ninja generator

from lib_util import cxx_findfiles

def gen_cmake(all_files, includedirs, prj_name, buildfox_name, cmd_env, filename = "CMakeLists.txt"):
	text = r"""# generated by BuildFox
cmake_minimum_required(VERSION 2.8.3)
project(%s)
include_directories("%s")
add_custom_target(
  build
  ALL %s
  WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR}
  VERBATIM
  %s
)
"""

	if cmd_env:
		for chr in ["\\", "\"", "(", ")", "#", "^"]:
			cmd_env = cmd_env.replace(chr, "\\" + chr)
		cmd_env = cmd_env.replace("$", "\\$")

	all_files = ["\"%s\"" % file for file in cxx_findfiles(all_files)]
	includedirs = ["."] + includedirs

	with open(filename, "w") as f:
		f.write(text % (
			prj_name,
			";".join(includedirs),
			cmd_env + " COMMAND ninja" if cmd_env else "ninja",
			"SOURCES " + " ".join(all_files) if all_files else ""
		))