# BuildFox ninja generator

def gen_make(buildfox_name, filename = "Makefile"):
	text = r"""# generated by BuildFox
all: configure compile
configure:
	bf%s
compile:
	ninja
clean:
	ninja -t clean
"""
	with open(filename, "w") as f:
		f.write(text % (
			" -i " + buildfox_name if buildfox_name != "build.fox" else ""
		))